---
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  # Only post codecov comments when coverage changes
  require_changes: true
  require_base: true
  require_head: true
  branches: null

coverage:
  status:
    project:
      default:
        # Allow the coverage to drop by 0.5%
        threshold: 0.5%
