---
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  # Only post codecov comments when coverage changes
  require_changes: true
  require_base: true
  require_head: true
  branches: null
