# Configuration file for Mega-Linter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: master # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - HTML_DJLINT
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD
  - DOCKERFILE_HADOLINT
  - CREDENTIALS_SECRETLINT
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY
DISABLE:
  - COPYPASTE # Comment to disable checks of abusive copy-pastes
  - SPELL # Comment to disable checks of spelling mistakes # - SPELL # Uncomment to disable checks of spelling mistakes
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - build
  - build-ext
  - build-dev
  - cypress-coverage
  - .nyc_output
  - .parcel-cache
FILTER_REGEX_EXCLUDE: (LICENSE|\.codecov.yml|CHANGELOG.md|src/vendors/explorer/*|src/vendors/oasisscan/*)
SHOW_ELAPSED_TIME: true
REPOSITORY_CHECKOV_ARGUMENTS:
  - --skip-path
  - docker/
  - --skip-path
  - src/locales/.*/translation.json
  - --skip-path
  - src/vendors/explorer/swagger.yml
  - --skip-path
  - src/vendors/oasisscan/swagger3.yml
REPOSITORY_GITLEAKS_CONFIG_FILE: ./.github/.gitleaks.toml
